<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_1_Data_dividation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day-1

In [87]:
# Machine learning ===>
# data(50)===> x(input data), y(Target data)
# x====> x_train , x_test
# y====> y_train , y_test

#  for machine training we will pass (x_train, y_train)

#  for machine testing we will pass (x_test)-----> y_pred


# 1+1 = 2
# 1+2 = 3
# 1+4 = 5
# 1+6 = 7
# 1+7 = 8
# 1+8 = 9


# x =(1+1, 1+2, 1+4,.........1+8)
# y=(2,3,,5,7,8,9)

# x_train = (1+1,1+2,1+4,1+6)
# x_test = (1+7,1+8)

# y_train =(2,3,5,7)
# y_test = (8,9)

In [88]:
import pandas as pd

In [89]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [90]:
# df.isnull().sum()

In [91]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [92]:
# df.isnull().sum()

In [93]:
x=df.drop(columns=['has_covid'])   ## Input data
# x

In [94]:
y=df['has_covid']   # Target or Output data
# y

In [95]:
from sklearn.model_selection import train_test_split

In [96]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [97]:
print("Total data shape : ", df.shape)
print("..............................")
print("Input data shape : ", x.shape)
print("x_train shape : ", x_train.shape)
print("x_test shape : ", x_test.shape)
print("..............................")
print("Target data shape :", y.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape : ", y_test.shape)

Total data shape :  (100, 6)
..............................
Input data shape :  (100, 5)
x_train shape :  (80, 5)
x_test shape :  (20, 5)
..............................
Target data shape : (100,)
y_train shape :  (80,)
y_test shape :  (20,)

In [98]:
pl=pd.read_csv("/content/placement - placement.csv")
pl.head(3)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1

In [99]:
pl.shape

(100, 3)

In [100]:
pl.isnull().sum()

cgpa            0
resume_score    0
placed          0
dtype: int64

In [101]:
x=pl.drop(columns=['placed'])   # input data
x

    cgpa  resume_score
0   8.14          6.52
1   6.17          5.17
2   8.27          8.86
3   6.88          7.27
4   7.52          7.30
..   ...           ...
95  6.33          6.38
96  8.23          7.76
97  6.65          7.78
98  8.14          5.63
99  6.09          6.61

[100 rows x 2 columns]

In [102]:
y=pl['placed']        ### Output data
y

0     1
1     0
2     1
3     1
4     1
     ..
95    0
96    1
97    0
98    1
99    0
Name: placed, Length: 100, dtype: int64

In [103]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=38)

In [104]:
print("Total data shape : ", pl.shape)
print("..............................")
print("Input data shape : ", x.shape)
print("x_train shape : ", x_train.shape)
print("x_test shape : ", x_test.shape)
print("..............................")
print("Target data shape :", y.shape)
print("y_train shape : ", y_train.shape)
print("y_test shape : ", y_test.shape)

Total data shape :  (100, 3)
..............................
Input data shape :  (100, 2)
x_train shape :  (80, 2)
x_test shape :  (20, 2)
..............................
Target data shape : (100,)
y_train shape :  (80,)
y_test shape :  (20,)

# Day-2

In [105]:
import numpy as np
import pandas as pd

In [106]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [107]:
# df.isnull().sum()

In [108]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [109]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [110]:
df=df.drop(columns=['city'])
df

    age  gender  fever   cough has_covid
0    60    Male  103.0    Mild        No
1    27    Male  100.0    Mild       Yes
2    42    Male  101.0    Mild        No
3    31  Female   98.0    Mild        No
4    65  Female  101.0    Mild        No
..  ...     ...    ...     ...       ...
95   12  Female  104.0    Mild        No
96   51  Female  101.0  Strong       Yes
97   20  Female  101.0    Mild        No
98    5  Female   98.0  Strong        No
99   10  Female   98.0  Strong       Yes

[100 rows x 5 columns]

In [111]:
df['gender']=df['gender'].map({'Male':1,'Female':0})
df['cough']=df['cough'].map({'Mild':1,'Strong':0})
df['has_covid']=df['has_covid'].map({'Yes':1,'No':0})
df

    age  gender  fever  cough  has_covid
0    60       1  103.0      1          0
1    27       1  100.0      1          1
2    42       1  101.0      1          0
3    31       0   98.0      1          0
4    65       0  101.0      1          0
..  ...     ...    ...    ...        ...
95   12       0  104.0      1          0
96   51       0  101.0      0          1
97   20       0  101.0      1          0
98    5       0   98.0      0          0
99   10       0   98.0      0          1

[100 rows x 5 columns]

In [115]:
x=df.drop(columns=['has_covid'])
x

    age  gender  fever  cough
0    60       1  103.0      1
1    27       1  100.0      1
2    42       1  101.0      1
3    31       0   98.0      1
4    65       0  101.0      1
..  ...     ...    ...    ...
95   12       0  104.0      1
96   51       0  101.0      0
97   20       0  101.0      1
98    5       0   98.0      0
99   10       0   98.0      0

[100 rows x 4 columns]

In [116]:
y=df['has_covid']
y

0     0
1     1
2     0
3     0
4     0
     ..
95    0
96    1
97    0
98    0
99    1
Name: has_covid, Length: 100, dtype: int64

In [117]:
from sklearn.model_selection import train_test_split

In [119]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [120]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  80.00   80.00   80.00  80.00
mean   42.91    0.41  100.98   0.60
std    24.47    0.50    1.93   0.49
min     5.00    0.00   98.00   0.00
25%    20.00    0.00  100.00   0.00
50%    42.00    0.00  101.00   1.00
75%    65.00    1.00  102.00   1.00
max    84.00    1.00  104.00   1.00

In [121]:
from sklearn.preprocessing import StandardScaler

In [122]:
sc=StandardScaler()

In [124]:
x_train_sc=sc.fit_transform(x_train)  # fit means learn the parameters and transform means apply on that

In [126]:
x_train_new=pd.DataFrame(x_train_sc,columns=x_train.columns)
x_train_new

         age    gender     fever     cough
0   1.566141 -0.837931  0.009126  0.816497
1  -1.558945 -0.837931 -0.512343  0.816497
2  -0.983271 -0.837931 -0.512343  0.816497
3  -0.654315  1.193416 -0.512343  0.816497
4   1.237185 -0.837931  1.052064  0.816497
..       ...       ...       ...       ...
75 -0.777674 -0.837931  0.530595 -1.224745
76  1.319424 -0.837931  1.573533 -1.224745
77  0.332554  1.193416  1.573533  0.816497
78  1.607261 -0.837931  0.530595 -1.224745
79 -1.312228 -0.837931 -0.512343 -1.224745

[80 rows x 4 columns]

In [127]:
type(x_train_new)

pandas.core.frame.DataFrame

In [128]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00    0.00  -0.00   0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -1.22
25%    -0.94   -0.84  -0.51  -1.22
50%    -0.04   -0.84   0.01   0.82
75%     0.91    1.19   0.53   0.82
max     1.69    1.19   1.57   0.82