<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_4_MinMaxScaling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 7-04-2026

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Normalization ----> using MinMaxScaling

# min->>>0 , max -->>> 1

In [ ]:
#  play store----> different app ---> 1 app downloads 4.2k , 2nd app download 2.3M,
#  1 app 640
# in this condition , if i apply any operation then it will return huge number and we can not
#  perform any visualization because it will create a zig-Zag situation

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [ ]:
df=df.dropna()

In [ ]:
df=df.drop(columns=['city'])

In [ ]:
df.head(2)

   age gender  fever cough has_covid
0   60   Male  103.0  Mild        No
1   27   Male  100.0  Mild       Yes

In [ ]:
# step 1 :: convert categorical data into numerical data

df['gender']=df['gender'].map({'Male':0,'Female':1})
df['cough']=df['cough'].map({'Mild':0,'Strong':1,'Strong':2})
df['has_covid']=df['has_covid'].map({'Yes':1,'No':0})
df

    age  gender  fever  cough  has_covid
0    60       0  103.0      0          0
1    27       0  100.0      0          1
2    42       0  101.0      0          0
3    31       1   98.0      0          0
4    65       1  101.0      0          0
..  ...     ...    ...    ...        ...
95   12       1  104.0      0          0
96   51       1  101.0      2          1
97   20       1  101.0      0          0
98    5       1   98.0      2          0
99   10       1   98.0      2          1

[90 rows x 5 columns]

In [ ]:
## step-2 data dividation

x=df.drop(columns=['has_covid'])
y=df['has_covid']

In [ ]:
x.head(2)

0    0
1    1
Name: has_covid, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

         age  gender   fever  cough
count  72.00   72.00   72.00  72.00
mean   43.53    0.64  100.74   0.69
std    25.30    0.48    2.12   0.96
min     5.00    0.00   98.00   0.00
25%    19.75    0.00   99.00   0.00
50%    47.00    1.00  101.00   0.00
75%    65.25    1.00  102.25   2.00
max    83.00    1.00  104.00   2.00

In [ ]:
## step -3 Apply MinMaxScaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
mn

MinMaxScaler()

In [ ]:
x_train_mn=mn.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_mn, columns = x.columns)

In [ ]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  72.00   72.00  72.00  72.00
mean    0.49    0.64   0.46   0.35
std     0.32    0.48   0.35   0.48
min     0.00    0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00
50%     0.54    1.00   0.50   0.00
75%     0.77    1.00   0.71   1.00
max     1.00    1.00   1.00   1.00

In [ ]:








#  practice -->>> data 2

In [ ]:
df=pd.read_csv("/content/placement - placement.csv")
df.head(2)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [ ]:
# step -2 data dividation
x=df.drop(columns=['placed'])
y=df['placed']

In [ ]:

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
np.round(x_train.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    6.95          7.00
std     1.13          1.01
min     5.27          4.95
25%     6.00          6.28
50%     6.62          7.15
75%     8.06          7.69
max     9.31          9.06

In [ ]:
# step -3 apply MinMaxScaler

In [ ]:
mn=MinMaxScaler()
mn

MinMaxScaler()

In [ ]:
x_train_mn=mn.fit_transform(x_train)

In [ ]:
x_train_new=pd.DataFrame(x_train_mn, columns = x.columns)

In [ ]:
np.round(x_train_new.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    0.42          0.50
std     0.28          0.25
min     0.00          0.00
25%     0.18          0.32
50%     0.33          0.54
75%     0.69          0.67
max     1.00          1.00