<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Machine_learning/ML_8_Churn_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Churn_Modelling - Churn_Modelling.csv")
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [ ]:
df=df.drop(columns=['RowNumber','CustomerId','Surname','Tenure'])
df.head(2)

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,83807.86,1,0,1,112542.58,0

In [ ]:
df=df.dropna()
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
x=df.drop(columns=['Exited'])
y=df['Exited']

x.head(2)
# y.head(2)

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,0.00,1,1,1,101348.88
1,608,Spain,Female,41,83807.86,1,0,1,112542.58

In [ ]:
# # Encoding (Label , Ordinal , Onehot , get_dummies)

## Label encoding
#  gender --->> Male / Female ----> 0 / 1

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

x['Gender_Label'] = le.fit_transform(x['Gender'])

x.head(2)

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label
0,619,France,Female,42,0.00,1,1,1,101348.88,0
1,608,Spain,Female,41,83807.86,1,0,1,112542.58,0

In [ ]:
## Ordinal encoding Geography

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

x['Geography_Ordinal'] = oe.fit_transform(x[['Geography']])

x.head(2)

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label,Geography_Ordinal
0,619,France,Female,42,0.00,1,1,1,101348.88,0,0.0
1,608,Spain,Female,41,83807.86,1,0,1,112542.58,0,2.0

In [ ]:

## One hot encoding

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

Geo_encode=ohe.fit_transform(x[['Geography']])



Geo_encode_df=pd.DataFrame(Geo_encode,columns=ohe.get_feature_names_out(['Geography']))

Geo_encode_df.head(2)

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0

In [ ]:
x=pd.concat([x,Geo_encode_df],axis=1)
x.head(2)

,CreditScore,Geography,Gender,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label,Geography_Ordinal,Geography_France,Geography_Germany,Geography_Spain
0,619,France,Female,42,0.00,1,1,1,101348.88,0,0.0,1.0,0.0,0.0
1,608,Spain,Female,41,83807.86,1,0,1,112542.58,0,2.0,0.0,0.0,1.0

In [ ]:
# get_dummies

x=pd.get_dummies(x,columns=['Gender'],drop_first=True)
x.head(2)

,CreditScore,Geography,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label,Geography_Ordinal,Geography_France,Geography_Germany,Geography_Spain,Gender_Male
0,619,France,42,0.00,1,1,1,101348.88,0,0.0,1.0,0.0,0.0,False
1,608,Spain,41,83807.86,1,0,1,112542.58,0,2.0,0.0,0.0,1.0,False

In [ ]:
## standardization

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

num_cols=['CreditScore','Age','Balance','NumOfProducts','EstimatedSalary']

x[num_cols]=sc.fit_transform(x[num_cols])

x.head(2)

,CreditScore,Geography,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label,Geography_Ordinal,Geography_France,Geography_Germany,Geography_Spain,Gender_Male
0,-0.326221,France,0.293517,-1.225848,-0.911583,1,1,0.021886,0,0.0,1.0,0.0,0.0,False
1,-0.440036,Spain,0.198164,0.117350,-0.911583,0,1,0.216534,0,2.0,0.0,0.0,1.0,False

In [ ]:
#  normalization

from sklearn.preprocessing import MinMaxScaler

mn=MinMaxScaler()

x[num_cols]=mn.fit_transform(x[num_cols])

x.head(2)

,CreditScore,Geography,Age,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Gender_Label,Geography_Ordinal,Geography_France,Geography_Germany,Geography_Spain,Gender_Male
0,0.538,France,0.324324,0.000000,0.0,1,1,0.506735,0,0.0,1.0,0.0,0.0,False
1,0.516,Spain,0.310811,0.334031,0.0,0,1,0.562709,0,2.0,0.0,0.0,1.0,False