<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/pandas_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [ ]:
### top data check , we will use df.head(), by default it returns top 5 rows.
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
###Bottom data check , we will use df.tail(), by default it returns last 5 rows.
df.tail(3)

    age  gender  fever   cough       city has_covid
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
### if you want random indexed data , then we will use df.sample(), by default it will return single row.
df.sample(3)

    age gender  fever   cough       city has_covid
67   65   Male   99.0    Mild  Bangalore        No
89   46   Male  103.0  Strong  Bangalore        No
44   20   Male  102.0  Strong      Delhi        No

In [ ]:
### if you want check data type of each column use df.dtypes()
df.dtypes

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [ ]:
### if we want to check overall information then we will use df.info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        100 non-null    int64
 1   gender     100 non-null    object
 2   fever      90 non-null     float64
 3   cough      100 non-null    object
 4   city       100 non-null    object
 5   has_covid  100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [ ]:
# x = 0-100
#50% = 50
# x=1,2,3,4,5
# mean=(1+2+3+4+5)/5 = 3

In [ ]:
# if you want to check statical view of data , then you can use df.describe()
df.describe()

              age       fever
count  100.000000   90.000000
mean    44.220000  100.844444
std     24.878931    2.054926
min      5.000000   98.000000
25%     20.000000   99.000000
50%     45.000000  101.000000
75%     66.500000  102.750000
max     84.000000  104.000000

In [ ]:
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [ ]:
#### if you want chcek missing data in df , then you will use df.isnull().sum()
df.isnull().sum()     # here fever has 10 missing values

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
# x = 1,2,3,nan,5
#mean= (1+2+3+5)/4   = 11/4  =2.75
# we will fill this value in this missing data
# x = 1,2,3,2.75,5

In [ ]:
df['fever']= df['fever'].fillna(df['fever'].mean())

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
df.head(1)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No

In [ ]:
### if you want categorical data, and you want to chcek total sub-categories the
# we will use df['column name'].value_count()

In [ ]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [ ]:
df['gender']= df['gender'].map({"Female":1, "Male":0})

In [ ]:
df.head(5)

   age  gender  fever cough     city has_covid
0   60       0  103.0  Mild  Kolkata        No
1   27       0  100.0  Mild    Delhi       Yes
2   42       0  101.0  Mild    Delhi        No
3   31       1   98.0  Mild  Kolkata        No
4   65       1  101.0  Mild   Mumbai        No

In [ ]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [ ]:
df['cough']= df['cough'].map({"Mild":1, "Strong":2,})

In [ ]:
df.sample()

    age  gender       fever  cough     city has_covid
56   71       0  100.844444      2  Kolkata        No

In [ ]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df['city']= df['city'].map({"Kolkata":1, "Bangalore":2,"Delhi":3,"Mumbai":4})

In [ ]:
df.sample()

    age  gender  fever  cough  city has_covid
38   49       1  101.0      1     3       Yes

In [ ]:
df['has_covid'].value_counts()

has_covid
No     55
Yes    45
Name: count, dtype: int64

In [ ]:
df['has_covid']= df['has_covid'].map({"No":0, "Yes":1})

In [ ]:
df.sample(5)

    age  gender  fever  cough  city  has_covid
58   23       0   98.0      2     4          1
28   16       0  104.0      1     1          0
33   26       1   98.0      1     1          0
23   80       1   98.0      1     3          1
72   83       1  101.0      1     1          0