<a href="https://colab.research.google.com/github/Chandrapraksh-prajapat/Regex/blob/main/Advance_Python/Pandas/pandas_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np
import pandas as pd

In [29]:
df=pd.read_csv('/content/placement - placement.csv')
df

    cgpa  resume_score  placed
0   8.14          6.52       1
1   6.17          5.17       0
2   8.27          8.86       1
3   6.88          7.27       1
4   7.52          7.30       1
..   ...           ...     ...
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

[100 rows x 3 columns]

In [30]:
# x = df.astype(int)    # type conversion

df['cgpa']=df['cgpa'].astype(int)
df

    cgpa  resume_score  placed
0      8          6.52       1
1      6          5.17       0
2      8          8.86       1
3      6          7.27       1
4      7          7.30       1
..   ...           ...     ...
95     6          6.38       0
96     8          7.76       1
97     6          7.78       0
98     8          5.63       1
99     6          6.61       0

[100 rows x 3 columns]

In [31]:

df['resume_score']=df['resume_score'].astype(int)    # convert float to integer
df

    cgpa  resume_score  placed
0      8             6       1
1      6             5       0
2      8             8       1
3      6             7       1
4      7             7       1
..   ...           ...     ...
95     6             6       0
96     8             7       1
97     6             7       0
98     8             5       1
99     6             6       0

[100 rows x 3 columns]

In [40]:
df['cgpa']=df['cgpa'].add(10)    # add 10 to cgpa
df

# df['cgpa']=df['cgpa'].sub(10)    # subtract 10 from cgpa
# df

    cgpa  resume_score  placed
0     18             6       1
1     16             5       0
2     18             8       1
3     16             7       1
4     17             7       1
..   ...           ...     ...
95    16             6       0
96    18             7       1
97    16             7       0
98    18             5       1
99    16             6       0

[100 rows x 3 columns]

In [41]:
df.describe()

             cgpa  resume_score      placed
count  100.000000    100.000000  100.000000
mean    16.470000      6.470000    0.500000
std      1.201472      0.999545    0.502519
min     15.000000      4.000000    0.000000
25%     15.000000      6.000000    0.000000
50%     16.000000      7.000000    0.500000
75%     18.000000      7.000000    1.000000
max     19.000000      9.000000    1.000000

In [42]:
r=df['cgpa'].mean()
r

np.float64(16.47)

In [43]:

s=df['cgpa'].median()
s

16.0

In [44]:

g=df.filter(items=['cgpa','placed'])
g


df[['cgpa','placed']]           ###second option for filtering

    cgpa  placed
0     18       1
1     16       0
2     18       1
3     16       1
4     17       1
..   ...     ...
95    16       0
96    18       1
97    16       0
98    18       1
99    16       0

[100 rows x 2 columns]

In [45]:
s=df.filter(items=[5,6],axis=0)     #axis=0   means row wise operation
s

   cgpa  resume_score  placed
5    18             6       1
6    15             7       0

In [ ]:
s=df.to_dict()
s

In [ ]:
q=df.to_string()
q

'    cgpa  resume_score  placed\n0     18             6       1\n1     16             5       0\n2     18             8       1\n3     16             7       1\n4     17             7       1\n5     18             6       1\n6     15             7       0\n7     16             6       0\n8     16             6       0\n9     17             7       1\n10    16             6       0\n11    15             6       0\n12    16             7       0\n13    18             5       1\n14    17             6       1\n15    18             5       1\n16    18             7       1\n17    17             8       1\n18    15             5       0\n19    16             8       1\n20    15             8       0\n21    16             7       0\n22    16             5       0\n23    16             7       0\n24    18             6       1\n25    17             5       1\n26    16             6       0\n27    15             6       0\n28    17             7       1\n29    16             7       0\n30    17             7       1\n31    15             7       0\n32    15             7       0\n33    18             7       1\n34    18             7       1\n35    18             7       1\n36    18             7       1\n37    19             8       1\n38    16             8       0\n39    17             6       1\n40    18             5       1\n41    18             5       1\n42    16             6       1\n43    18             7       1\n44    15             5       0\n45    18             5       1\n46    15             5       0\n47    17             8       1\n48    15             6       0\n49    15             6       0\n50    18             6       1\n51    16             7       0\n52    15             7       0\n53    16             7       0\n54    15             7       0\n55    16             6       1\n56    16             6       0\n57    16             7       0\n58    16             7       0\n59    15             7       0\n60    15             6       0\n61    16             7       1\n62    15             8       0\n63    18             7       1\n64    17             8       1\n65    16             8       0\n66    18             8       1\n67    16             6       1\n68    16             7       0\n69    18             9       1\n70    17             7       1\n71    17             8       1\n72    17             7       1\n73    15             6       0\n74    15             7       0\n75    16             7       1\n76    19             5       1\n77    15             6       0\n78    15             5       0\n79    15             7       0\n80    17             7       1\n81    16             6       0\n82    17             6       1\n83    17             8       1\n84    15             6       0\n85    16             5       0\n86    16             5       0\n87    15             5       0\n88    18             6       1\n89    15             7       0\n90    15             5       0\n91    18             6       1\n92    15             6       0\n93    19             7       1\n94    18             4       1\n95    16             6       0\n96    18             7       1\n97    16             7       0\n98    18             5       1\n99    16             6       0'

In [ ]:
idx=df.columns
idx

Index(['cgpa', 'resume_score', 'placed'], dtype='object')

In [ ]:
label=df.columns[0]      #first column label
label

'cgpa'

In [ ]:
p=df.columns.to_list()
p

['cgpa', 'resume_score', 'placed']

In [ ]:
df=df.copy()

In [ ]:
p=df.rename(columns={'cgpa':'updated_cgpa','resume_score':'updated_resume_score'})
p

    updated_cgpa  updated_resume_score  placed
0             18                     6       1
1             16                     5       0
2             18                     8       1
3             16                     7       1
4             17                     7       1
..           ...                   ...     ...
95            16                     6       0
96            18                     7       1
97            16                     7       0
98            18                     5       1
99            16                     6       0

[100 rows x 3 columns]

In [ ]:
df['half']=df['resume_score'].where(df['resume_score']>5, other=0)     # search in dataframe using where
df.head(5)

   cgpa  resume_score  placed  half
0    18             6       1     6
1    16             5       0     0
2    18             8       1     8
3    16             7       1     7
4    17             7       1     7

In [ ]:
df=pd.read_csv("/content/tips - tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
# filter row from 11 to 13
# extract 3 columns
# 2 column name rename
# new column name ===> male customer
# total bill column convert to integer
# data 1-->1 column data type, top 6 data, data export csv , xlsx


# df.filter(items=[11,12,13],axis=0)
df.iloc[11:14]

    total_bill   tip     sex smoker  day    time  size male_customer
11          35  5.00  Female     No  Sun  Dinner     4             0
12          15  1.57    Male     No  Sun  Dinner     2          Male
13          18  3.00    Male     No  Sun  Dinner     4          Male

In [ ]:
df.iloc[ : ,0:3]

     total_bill   tip     sex
0            16  1.01  Female
1            10  1.66    Male
2            21  3.50    Male
3            23  3.31    Male
4            24  3.61  Female
..          ...   ...     ...
239          29  5.92    Male
240          27  2.00  Female
241          22  2.00    Male
242          17  1.75    Male
243          18  3.00  Female

[244 rows x 3 columns]

In [ ]:
p=df.rename(columns={'sex':'Gender','total_bill':'price'})
p

     price   tip  Gender smoker   day    time  size
0    16.99  1.01  Female     No   Sun  Dinner     2
1    10.34  1.66    Male     No   Sun  Dinner     3
2    21.01  3.50    Male     No   Sun  Dinner     3
3    23.68  3.31    Male     No   Sun  Dinner     2
4    24.59  3.61  Female     No   Sun  Dinner     4
..     ...   ...     ...    ...   ...     ...   ...
239  29.03  5.92    Male     No   Sat  Dinner     3
240  27.18  2.00  Female    Yes   Sat  Dinner     2
241  22.67  2.00    Male    Yes   Sat  Dinner     2
242  17.82  1.75    Male     No   Sat  Dinner     2
243  18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:

df['male_customer']=df['sex'].where(df['sex']=='Male',other=0)
df

     total_bill   tip     sex smoker   day    time  size male_customer
0         16.99  1.01  Female     No   Sun  Dinner     2             0
1         10.34  1.66    Male     No   Sun  Dinner     3          Male
2         21.01  3.50    Male     No   Sun  Dinner     3          Male
3         23.68  3.31    Male     No   Sun  Dinner     2          Male
4         24.59  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3          Male
240       27.18  2.00  Female    Yes   Sat  Dinner     2             0
241       22.67  2.00    Male    Yes   Sat  Dinner     2          Male
242       17.82  1.75    Male     No   Sat  Dinner     2          Male
243       18.78  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [ ]:
df['total_bill']=df['total_bill'].astype(int)
df

     total_bill   tip     sex smoker   day    time  size male_customer
0            16  1.01  Female     No   Sun  Dinner     2             0
1            10  1.66    Male     No   Sun  Dinner     3          Male
2            21  3.50    Male     No   Sun  Dinner     3          Male
3            23  3.31    Male     No   Sun  Dinner     2          Male
4            24  3.61  Female     No   Sun  Dinner     4             0
..          ...   ...     ...    ...   ...     ...   ...           ...
239          29  5.92    Male     No   Sat  Dinner     3          Male
240          27  2.00  Female    Yes   Sat  Dinner     2             0
241          22  2.00    Male    Yes   Sat  Dinner     2          Male
242          17  1.75    Male     No   Sat  Dinner     2          Male
243          18  3.00  Female     No  Thur  Dinner     2             0

[244 rows x 8 columns]

In [ ]:
# data 1-->1 column data type, top 6 data, data export csv , xlsx

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   total_bill     244 non-null    int64
 1   tip            244 non-null    float64
 2   sex            244 non-null    object
 3   smoker         244 non-null    object
 4   day            244 non-null    object
 5   time           244 non-null    object
 6   size           244 non-null    int64
 7   male_customer  244 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.4+ KB

In [ ]:
a=df.head(6)
a

   total_bill   tip     sex smoker  day    time  size male_customer
0          16  1.01  Female     No  Sun  Dinner     2             0
1          10  1.66    Male     No  Sun  Dinner     3          Male
2          21  3.50    Male     No  Sun  Dinner     3          Male
3          23  3.31    Male     No  Sun  Dinner     2          Male
4          24  3.61  Female     No  Sun  Dinner     4             0
5          25  4.71    Male     No  Sun  Dinner     4          Male

In [ ]:
# data export to csv
a.to_csv('data.csv')

In [ ]:
# data export to excel
a.to_excel('data.xlsx')

In [ ]:
# Data --->

# (1). Numerical ---> Coontinuous data --->we can divide furthur.

# Salary ---> 20500.60, weight = 70.54, distance(jaipur to delhi)=270.78 km, height, Age

# (2). Categorical ---> Descrete data ---> we cannot divide furthur.

# Gender(M,F), Marital Status (M,U), Number of employees in an office,

# covid data ---> has_covid(y,n)--> map --> (1,0) # customer cafe ---> bill pay ---> 453.25 rupees